### ISSUE TITLE
tweets about GPU.js are completely irrelevant

### ISSUE THREAD

**Issue by robertleeplummerjr** [cool-robot-pals/webstandardsbot#8]
I regularly look for tweets that are about GPU.js because I've spent the last three years or so of my life stabilizing it and working hard so it can work on desktop browsers, mobile browsers, native environments (expo), and node.  I find the tweets regarding any relationship to it offensive and completely unrelated.

I recently wrote an article about why GPU.js is such an important project: https://medium.com/swlh/javascript-for-machine-learning-get-a-real-language-628000886683 in which it competes with other modern-day APIs such as tensorflow.js and is more practical and gives less technological debt.

I don't think that this library (webstandardsbot) was intended to mislead anybody, but the fact of the matter is: that is the case here specifically with GPU.js.

Would it be possible to remove said tweets and possibly alter the library so that it better represents what is and is not in the bot's words "broke" or "woke"?

**Comment by walaura** [comment]
hiya! thanks for the feedback. I've taken it to the team and we'll discuss this first thing monday! If you wanna speed up things it'd be super helpful if you could submit a PR removing the offending line.

In the meanwhile, I hope it's clear that the bot is a humorous take on autogenerating commonplace tweets like 'we dont need react now that theres webcomponents' or 'we dont need jquery after queryselectorall'? I'm honestly interested in your answer because If it's not clear this is the intention we have failed at making the point this project was trying to make and need to do better in that regard.

thanks!

**Comment by robertleeplummerjr** [comment]
Ah, that makes sense.  Maybe just change the name of the bot or its description so that it is more apparent it is joking?

**Comment by robertleeplummerjr** [comment]
I didn't get the humor, but now I see it as a compliment.  Ty guys for trying to poke humor at development.  We could use more of it.
